export const mutation = {
	SET_LOGGED_IN: 'SET_LOGGED_IN',
	SET_USER_URL: 'SET_USER_URL',
	SET_USER_ACCESS: 'SET_USER_ACCESS',
	UPDATE_USER_DETAILS: 'UPDATE_USER_DETAILS',
	CLEAR_USER_AVATAR: 'CLEAR_USER_AVATAR',
};

export const action = {
	SET_LOGGED_IN: 'SET_LOGGED_IN',
	SET_USER_URL: 'SET_USER_URL',
	CHECK_LOGIN_ON_SERVER: 'CHECK_LOGIN_ON_SERVER',
	LOGOUT_USER: 'LOGOUT_USER',
	UPDATE_USER_DETAILS_ON_SERVER: 'UPDATE_USER_DETAILS_ON_SERVER',
	CLEAR_USER_AVATAR: 'CLEAR_USER_AVATAR',
};

export const getter = {
	IS_LOGGED_IN: 'IS_LOGGED_IN',
	GET_USER_URL: 'GET_USER_URL',
	GET_USER_ROLE: 'GET_USER_ROLE',
	GET_USER_DETAILS: 'GET_USER_DETAILS',
	GET_USER_AVATAR: 'GET_USER_AVATAR',
};

export default {
	action,
	mutation,
	getter,
};
